### ISSUE TITLE
no setup.py

### ISSUE THREAD

**Issue by mariabenitocst** [kosiokarchev/clipppy#1]
how to install clipppy directly on python (without pip) if there is no `setup.py`?

Following this solution in [Stackoverflow](https://stackoverflow.com/questions/45112024/installing-a-github-package-without-setup-py), I am manually copying the files to `site-packages` (fingers crossed!)

**Comment by mariabenitocst** [comment]
For the above solution to work, I think you need to comment line 9 in `src/clipppy/__init__.py`, i.e.
`from ._version import __version__, version, __version_tuple__, version_tuple`

**Comment by kosiokarchev** [comment]
Since 3caf443 clipppy moved to a [pyproject.toml](https://packaging.python.org/en/latest/guides/writing-pyproject-toml/)-based installation, which [replaces the setup.py mechanism](https://packaging.python.org/en/latest/discussions/setup-py-deprecated/#setup-py-deprecated), so installation has to be done via pip (or some other similar tool like poetry).
However, you can still install from source (instead of a---currently very outdated---PyPI release) by cloning the repo and doing `pip install .` from the root directory. If installing from source, I'd recommend `pip install -e .` for an editable (in-place) install, which allows you to edit the files (e.g. pull latest updates and squash bugs).

PS I guess your method works as well (especially if you don't want to install all dependencies because you just need that one file... btw, pip has a `--no-dependencies` switch for this case), and would work even without tinkering if I hadn't set up automated versioning---sorry!
